import './globals.css';
import { Navbar } from '@/components';
import { Archivo, Manrope } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const archivo = Archivo({
  subsets: ['latin'],
  display: 'swap'
})

export const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
