import Hero from "@/sections/Landing/Hero";
import Steps from "@/components/Steps";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="text-white">
      <Hero />
      <Steps />
    </main>
  )
}
