import Hero from "@/sections/Landing/Hero"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="text-white">
      <Hero />
    </main>
  )
}
